#    _    _        _    ____ ____  ___ _____ _______   _______ ___  __  __ _     
#   / \  | |      / \  / ___|  _ \|_ _|_   _|_   _\ \ / /_   _/ _ \|  \/  | |    
#  / _ \ | |     / _ \| |   | |_) || |  | |   | |  \ V /  | || | | | |\/| | |    
# / ___ \| |___ / ___ \ |___|  _ < | |  | |   | |   | |_  | || |_| | |  | | |___ 
#/_/   \_\_____/_/   \_\____|_| \_\___| |_|   |_|   |_(_) |_| \___/|_|  |_|_____|
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 


#   ______                           __
#  / ____/__  ____  ___  _________ _/ /
# / / __/ _ \/ __ \/ _ \/ ___/ __ `/ / 
#/ /_/ /  __/ / / /  __/ /  / /_/ / /  
#\____/\___/_/ /_/\___/_/   \__,_/_/    

import = [
  "~/.config/alacritty/tokyo_colors.toml",
  "~/.config/alacritty/fonts.toml",
] 

live_config_reload = true


# _       ___           __             
#| |     / (_)___  ____/ /___ _      __
#| | /| / / / __ \/ __  / __ \ | /| / /
#| |/ |/ / / / / / /_/ / /_/ / |/ |/ / 
#|__/|__/_/_/ /_/\__,_/\____/|__/|__/  

[window]
padding = {x = 15, y = 15 }
dynamic_padding = true
opacity = 0.95
blur = true


#   _____                 _____            
#  / ___/______________  / / (_)___  ____ _
#  \__ \/ ___/ ___/ __ \/ / / / __ \/ __ `/
# ___/ / /__/ /  / /_/ / / / / / / / /_/ / 
#/____/\___/_/   \____/_/_/_/_/ /_/\__, /  
#                                 /____/   

[scrolling]
history = 1200
multiplier = 5


#   _____      __          __  _           
#  / ___/___  / /__  _____/ /_(_)___  ____ 
#  \__ \/ _ \/ / _ \/ ___/ __/ / __ \/ __ \
# ___/ /  __/ /  __/ /__/ /_/ / /_/ / / / /
#/____/\___/_/\___/\___/\__/_/\____/_/ /_/ 

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true


#   ______                          
#  / ____/_  ________________  _____
# / /   / / / / ___/ ___/ __ \/ ___/
#/ /___/ /_/ / /  (__  ) /_/ / /    
#\____/\__,_/_/  /____/\____/_/

[cursor]
style = "Beam"
blink_interval = 750
unfocused_hollow = true
thickness = 0.15
   
