#  ____ ___  _     ___  ____  ____ _____ ___  __  __ _     
# / ___/ _ \| |   / _ \|  _ \/ ___|_   _/ _ \|  \/  | |    
#| |  | | | | |  | | | | |_) \___ \ | || | | | |\/| | |    
#| |__| |_| | |__| |_| |  _ < ___) || || |_| | |  | | |___ 
# \____\___/|_____\___/|_| \_\____(_)_| \___/|_|  |_|_____|
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


#                _                           
#    ____  _____(_)___ ___  ____ ________  __
#   / __ \/ ___/ / __ `__ \/ __ `/ ___/ / / /
#  / /_/ / /  / / / / / / / /_/ / /  / /_/ / 
# / .___/_/  /_/_/ /_/ /_/\__,_/_/   \__, /  
#/_/                                /____/   

[colors.primary]
background = '#2d353b'
foreground = '#d3c6aa'

#  _______  ________________  _____
# / ___/ / / / ___/ ___/ __ \/ ___/
#/ /__/ /_/ / /  (__  ) /_/ / /    
#\___/\__,_/_/  /____/\____/_/     
                               
[colors.cursor]
text = "#9da9a0"
cursor = "#7a8478"


#                                     __
#   ____  ____  _________ ___  ____ _/ /
#  / __ \/ __ \/ ___/ __ `__ \/ __ `/ / 
# / / / / /_/ / /  / / / / / / /_/ / /  
#/_/ /_/\____/_/  /_/ /_/ /_/\__,_/_/

[colors.normal]
black = "#475258" 
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"


#    __         _       __    __ 
#   / /_  _____(_)___ _/ /_  / /_
#  / __ \/ ___/ / __ `/ __ \/ __/
# / /_/ / /  / / /_/ / / / / /_  
#/_.___/_/  /_/\__, /_/ /_/\__/  
#             /____/      

[colors.bright]
black = "#475258"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"
