#  ____ ___  _     ___  ____  ____ _____ ___  __  __ _     
# / ___/ _ \| |   / _ \|  _ \/ ___|_   _/ _ \|  \/  | |    
#| |  | | | | |  | | | | |_) \___ \ | || | | | |\/| | |    
#| |__| |_| | |__| |_| |  _ < ___) || || |_| | |  | | |___ 
# \____\___/|_____\___/|_| \_\____(_)_| \___/|_|  |_|_____|
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


#                _                           
#    ____  _____(_)___ ___  ____ ________  __
#   / __ \/ ___/ / __ `__ \/ __ `/ ___/ / / /
#  / /_/ / /  / / / / / / / /_/ / /  / /_/ / 
# / .___/_/  /_/_/ /_/ /_/\__,_/_/   \__, /  
#/_/                                /____/   

[colors.primary]
background = '#060D13'
foreground = '#C9C29C'


#  _______  ________________  _____
# / ___/ / / / ___/ ___/ __ \/ ___/
#/ /__/ /_/ / /  (__  ) /_/ / /    
#\___/\__,_/_/  /____/\____/_/     
                               
[colors.cursor]
text = '#23272A'
cursor = '#8CB7D9'


#                                     __
#   ____  ____  _________ ___  ____ _/ /
#  / __ \/ __ \/ ___/ __ `__ \/ __ `/ / 
# / / / / /_/ / /  / / / / / / /_/ / /  
#/_/ /_/\____/_/  /_/ /_/ /_/\__,_/_/

[colors.normal]
black = '#060D13'
red = '#AD1F1F'
green = '#4EAD1F'
yellow = '#AEA21F'
blue = '#1F6CAD'
magenta = '#931FAD'
cyan = '#1FADAD'
white = '#E9F3FB'


#    __         _       __    __ 
#   / /_  _____(_)___ _/ /_  / /_
#  / __ \/ ___/ / __ `/ __ \/ __/
# / /_/ / /  / / /_/ / / / / /_  
#/_.___/_/  /_/\__, /_/ /_/\__/  
#             /____/      

[colors.bright]
black = '#23272A'
red = '#D98C8C'
green = '#B0D98C'
yellow = '#D9D28C'
blue = '#8CB7D9'
magenta = '#CA8CD9'
cyan = '#8CD9D9'
white = '#ECECF9'
