# _____ ___  _   _ _____ ____ _____ ___  __  __ _     
#|  ___/ _ \| \ | |_   _/ ___|_   _/ _ \|  \/  | |    
#| |_ | | | |  \| | | | \___ \ | || | | | |\/| | |    
#|  _|| |_| | |\  | | |  ___) || || |_| | |  | | |___ 
#|_|   \___/|_| \_| |_| |____(_)_| \___/|_|  |_|_____|
#- - - - - - - - - - - - - - - - - - - - - - - - - - -


#    ____            __ 
#   / __/___  ____  / /_
#  / /_/ __ \/ __ \/ __/
# / __/ /_/ / / / / /_  
#/_/  \____/_/ /_/\__/  

[font]
normal.family = "JetBrainsMono Nerd Font"

size = 12.00
offset = { x = 0, y = 0}

