#  ____ ___  _     ___  ____  ____ _____ ___  __  __ _     
# / ___/ _ \| |   / _ \|  _ \/ ___|_   _/ _ \|  \/  | |    
#| |  | | | | |  | | | | |_) \___ \ | || | | | |\/| | |    
#| |__| |_| | |__| |_| |  _ < ___) || || |_| | |  | | |___ 
# \____\___/|_____\___/|_| \_\____(_)_| \___/|_|  |_|_____|
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


#                _                           
#    ____  _____(_)___ ___  ____ ________  __
#   / __ \/ ___/ / __ `__ \/ __ `/ ___/ / / /
#  / /_/ / /  / / / / / / / /_/ / /  / /_/ / 
# / .___/_/  /_/_/ /_/ /_/\__,_/_/   \__, /  
#/_/                                /____/   

[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'


#  _______  ________________  _____
# / ___/ / / / ___/ ___/ __ \/ ___/
#/ /__/ /_/ / /  (__  ) /_/ / /    
#\___/\__,_/_/  /____/\____/_/     
                               
[colors.cursor]
text = '#23272A'
cursor = '#8CB7D9'


#                                     __
#   ____  ____  _________ ___  ____ _/ /
#  / __ \/ __ \/ ___/ __ `__ \/ __ `/ / 
# / / / / /_/ / /  / / / / / / /_/ / /  
#/_/ /_/\____/_/  /_/ /_/ /_/\__,_/_/

[colors.normal]
black = '#32344a'
red = '#ff757f'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#787c99'


#    __         _       __    __ 
#   / /_  _____(_)___ _/ /_  / /_
#  / __ \/ ___/ / __ `/ __ \/ __/
# / /_/ / /  / / /_/ / / / / /_  
#/_.___/_/  /_/\__, /_/ /_/\__/  
#             /____/      

[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'
